# Generated by Django 5.1.1 on 2025-11-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Partner logo image', upload_to='partners/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this logo on the page')),
                ('url', models.URLField(blank=True, help_text='Optional link to partner website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'verbose_name_plural': 'Partner Logos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Partners', max_length=200)),
                ('heading', models.CharField(default="Let's Collaborate", max_length=200)),
                ('content', models.TextField(default='At Enterprises, we take pride in being the trusted thread supplier...', help_text='Main service page content')),
                ('show_partner_logos', models.BooleanField(default=True, help_text='Show partner logos section')),
                ('partner_section_title', models.CharField(default='Our Partners', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Page Content',
                'verbose_name_plural': 'Service Page Content',
            },
        ),
    ]
